"""
Global Oya exception and warning classes.
"""
from click import ClickException


class FimbuException(Exception):...

class CommandError(ClickException, FimbuException):...

class ImproperlyConfigured(FimbuException):...

class LoadMiddlewareError(FimbuException):...

class AppRegistryNotReady(FimbuException):...

class SuspiciousFileOperation(FimbuException):...


class NotSupportError(FimbuException):...

class DowngradeError(FimbuException):...
